name: Run DhanHQ Trading Bot

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  trade-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas numpy ta schedule python-dotenv

      - name: Debug: List Repository Files
        run: ls -R  # Lists all files to check if `orders.py` exists

      - name: Run trading bot
        env:
          DHAN_API_KEY: ${{ secrets.DHAN_API_KEY }}
          DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
        run: python orders.py  # Update this if file is inside a folder
